### PR TITLE
Adding the conference schedule

### PR DESCRIPTION
**Pull request by SaptakS**
- [x] Created the data file format to render the schedule
- [x] Fill up the data file with the schedule.

This should be ready for filling up with the schedule. Please take care of the data structure format in the `.yml` file. The talks can be of three different types:
- talk : Takes 1/4th width of the schedule (i.e. one room)
- keynote: Entire row width along with speaker name
- extra: Entire row, without speaker name (for break, networking, etc.)

### CODE REVIEW

**Comment by raukadah** [comment]
@SaptakS Can we hyperlink schedule with something like this https://deploy-preview-34--inpycon2021.netlify.app/#schedule ? So that we can share easily?

**Comment by raukadah** [comment]
@kalyan678 @RiteshAgrawal @anistark @palnabarun Please have a look. cc @abhishekmishragithub  @vipulgupta2048

**Comment by raukadah** [comment]
https://deploy-preview-34--inpycon2021.netlify.app/#schedule looks good, Thank you @SaptakS :1st_place_medal:

**Review by raukadah — APPROVED** [review]

**Review by anistark — APPROVED** [review]

**Comment by RiteshAgrawal** [comment]
"pm" from the time needs to be removed since we are having 24hr format

**Comment by raukadah** [comment]
> "pm" from the time needs to be removed since we are having 24hr format

Done

**Pull request merged**
