### PR TITLE
Open WorkShop and combo tickets

### PR DESCRIPTION
**Pull request by raukadah**
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>

### CODE REVIEW

**Comment by raukadah** [comment]
@inovizz @palnabarun @anistark Please have a look, thanks!

**Comment by raukadah** [comment]
Here is the preview: https://deploy-preview-23--inpycon2021.netlify.app/#tickets

**Review by inovizz — APPROVED** [review]

**Comment by inovizz** [comment]
image

**Comment by inovizz** [comment]
@raukadah - the combo ticket view looks broken. I think we can let it go and raise a hotfix to fix it later? Let me know.

**Comment by raukadah** [comment]
> @raukadah - the combo ticket view looks broken. I think we can let it go and raise a hotfix to fix it later? Let me know.

Yes sure, we can fix it in a seperate patch.

**Comment by palnabarun** [comment]
I don't think it is a non-blocking issue. This breaks the UI of the website.

@SaptakS -- what do you think?

**Comment by SaptakS** [comment]
Yes. We do need to fix this. I will add a commit to this PR after some time. Only quick solutions right now are either reduce font-size or increase height of the ticket card

**Comment by sayanchowdhury** [comment]
> Yes. We do need to fix this. I will add a commit to this PR after some time. Only quick solutions right now are either reduce font-size or increase height of the ticket card

Or maybe add a subtle? Title would be Combo Ticket, and Workshop and Conference Ticket as a subtitle?

**Comment by raukadah** [comment]
> > Yes. We do need to fix this. I will add a commit to this PR after some time. Only quick solutions right now are either reduce font-size or increase height of the ticket card
> 
> Or maybe add a subtle? Title would be Combo Ticket, and Workshop and Conference Ticket as a subtitle?

Changes made, and here is the preview
Screenshot from 2021-06-29 16-36-31

**Review by SaptakS — APPROVED** [review]
Looks ok to me

**Review by palnabarun — APPROVED** [review]
LGTM!

**Pull request merged**
