### PR TITLE
Updating buttons on cfp closing.

### PR DESCRIPTION
**Pull request by anistark**

### CODE REVIEW

**Comment by sayanchowdhury** [comment]
Should we update the secondary link to tickets as done in #18

**Comment by anistark** [comment]
> Should we update the secondary link to tickets as done in #18

Shouldn't primary button bring in more focus to it? Your call. Can remove primary and keep secondary only.

**Comment by sayanchowdhury** [comment]
> 
> Shouldn't primary button bring in more focus to it? Your call. Can remove primary and keep secondary only.

My idea is once the BoF closes, tickets moves to primary.

**Comment by sayanchowdhury** [comment]
I mean BoF stays primary but add tickets to secondary.

**Comment by anistark** [comment]
Reopening #18 .

**Pull request closed without merging**
