### PR TITLE
Add InfosecGirls and ALiAS as an outreach partner

### PR DESCRIPTION
**Pull request by abhishekmishragithub**
- Add InfosecGirls and ALiAS as an outreach partner
- Update communities.yml
- Add partner logo

### CODE REVIEW

**Comment by abhishekmishragithub** [comment]
image

The ALiAS logo is breaking the section.
@SaptakS can you please help with the image (CSS) issue.

**Comment by abhishekmishragithub** [comment]
@Sc0rpi0n101 if you get smaller logo then please provide else we need to fix this with CSS.
cc: @SaptakS

**Review by anistark — APPROVED** [review]

**Comment by SaptakS** [comment]
Fixed alignment:

image

**Comment by abhishekmishragithub** [comment]
Thanks @SaptakS  🙌🏼 

@raukadah @anistark, please review and merge this.

**Review by anistark — APPROVED** [review]

**Review by raukadah — APPROVED** [review]
Looks good https://deploy-preview-33--inpycon2021.netlify.app/

**Pull request merged**
